language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: jfong27-github
    token:
      secure: 20d84d202d8580dc4a7d21db7c7e6c5617c32940
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
